### ISSUE TITLE
Talos 1.3.5 LinkSpecController segfaulting following Sidero Metal Deployment

### ISSUE THREAD

**Issue by AlvesAlexander** [siderolabs/talos#6956]
### Description
Seeing the below segfault occur after deploying to a rack of 3x Dell PowerEdge r740 machines
### Logs
```
172.18.0.16: kern:    info: [2023-03-14T14:40:01.674091594Z]: init[1779]: segfault at 8 ip 0000000002617d86 sp 000000c001ff0c48 error 4 in init[400000+2510000]
172.18.0.16: kern:    info: [2023-03-14T14:40:01.805998594Z]: Code: 01 00 00 00 eb 52 48 8d 05 37 08 52 01 48 8b 9c 24 c8 0b 00 00 e8 ea 9c 49 fe 48 8b 8c 24 30 02 00 00 48 8b 51 10 48 8b 52 60 <48> 8b 72 08 48 8b 12 48 8b 58 18 48 39 70 20 74 07 b8 01 00 00 00
172.18.0.16: user: warning: [2023-03-14T14:40:02.057627594Z]: [talos] controller failed {"component": "controller-runtime", "controller": "network.LinkSpecController", "error": "controller \x5c"network.LinkSpecController\x5c" panicked: runtime error: invalid memory address or nil pointer dereference\x5cn\x5cngoroutine 488 [running]:\x5cnruntime/debug.Stack()\x5cn\x5ct/toolchain/go/src/runtime/debug/stack.go:24 +0x65\x5cngithub.com/cosi-project/runtime/pkg/controller/runtime.(*adapter).runOnce.func2()\x5cn\x5ct/.cache/mod/github.com/cosi-project/runtime@v0.2.1/pkg/controller/runtime/adapter.go:401 +0x5d\x5cnpanic({0x2d786e0, 0x57da970})\x5cn\x5ct/toolchain/go/src/runtime/panic.go:884 +0x212\x5cngithub.com/siderolabs/talos/internal/app/machined/pkg/controllers/network.(*LinkSpecController).syncLink(0x22?, {0x3b52c38, 0xc0009f2280}, {0x3b70900, 0xc000402080}, 0x1?, 0xc000b2b880, 0xc001ff1a38, 0xc001ff1a20, 0xc00125b500)\x5cn\x5ct/src/internal/app/machined/pkg/controllers/network/link_spec.go:227 +0x386\x5cngithub.com/siderolabs/talos/internal/app/machined/pkg/controllers/...
```
### Environment

- Talos version: 1.3.5
- Kubernetes version: 1.26.1
- Platform:   linux/amd64

**Comment by DmitriyMV** [comment]
Hello @AlvesAlexander, thank you for the bug report! 

Could you build installer (`make installer`) with #6959 applied and see what kind of log it would produce? The relevant line will contain `requested link has no info` and the number of additional fields.

**Comment by AlvesAlexander** [comment]
Having some trouble getting the installer working, however we were able to pin down the initial issue to a mistake in the config pointing to a bonded interface without any real interfaces assigned.

**Comment by smira** [comment]
@AlvesAlexander do you have a part of the (wrong) configuration with bonds so we could reproduce the problem?

**Comment by smira** [comment]
`panic` was fixed, if there's more info about the core issue, we're happy to look further
