### ISSUE TITLE
talosctl dashboard panic

### ISSUE THREAD

**Issue by buroa** [siderolabs/talos#7300]
## Bug Report

talosctl dashboard panic

### Logs

```
> talosctl dashboard
panic: open /proc/cmdline: no such file or directory

goroutine 1 [running]:
github.com/siderolabs/go-procfs/procfs.ProcCmdline.func1()
	/.cache/mod/github.com/siderolabs/go-procfs@v0.1.1/procfs/cmdline.go:129 +0x78
sync.(*Once).doSlow(0x140005dd880?, 0xe0?)
	/toolchain/go/src/sync/once.go:74 +0x104
sync.(*Once).Do(...)
	/toolchain/go/src/sync/once.go:65
github.com/siderolabs/go-procfs/procfs.ProcCmdline()
	/.cache/mod/github.com/siderolabs/go-procfs@v0.1.1/procfs/cmdline.go:126 +0x3c
github.com/siderolabs/talos/internal/pkg/dashboard.(*ConfigURLGrid).readTemplateFromKernelArgs(0x14000783a00?)
	/src/internal/pkg/dashboard/configurl.go:123 +0x1c
github.com/siderolabs/talos/internal/pkg/dashboard.NewConfigURLGrid({0x106e4e368, 0x14000e3f4d0}, 0x1400027be00)
	/src/internal/pkg/dashboard/configurl.go:60 +0x330
github.com/siderolabs/talos/internal/pkg/dashboard.buildDashboard({0x106e4e368, 0x14000e3f4d0}, 0x14000e24360, {0x14000ce1850, 0x3, 0x14000100000?})
	/src/internal/pkg/dashboard/dashboard.go:163 +0x6f0
github.com/siderolabs/talos/internal/pkg/dashboard.Run({0x106e4e368, 0x14000e3f4d0}, 0x14000e3f4a0?, {0x14000ce1850?, 0x0?, 0x0?})
	/src/internal/pkg/dashboard/dashboard.go:296 +0x34
github.com/siderolabs/talos/cmd/talosctl/cmd/talos.glob..func17.1({0x106e4e368, 0x14000e3f4d0}, 0x14000e208b0?)
	/src/cmd/talosctl/cmd/talos/dashboard.go:41 +0xf8
github.com/siderolabs/talos/cmd/talosctl/pkg/talos/global.(*Args).WithClient.func1({0x106e4e2c0?, 0x14000dfb770?}, 0x14000e24360)
	/src/cmd/talosctl/pkg/talos/global/client.go:93 +0x108
github.com/siderolabs/talos/cmd/talosctl/pkg/talos/global.(*Args).WithClientNoNodes.func1({0x106e4e2c0, 0x14000dfb770})
	/src/cmd/talosctl/pkg/talos/global/client.go:66 +0x50c
github.com/siderolabs/talos/pkg/cli.WithContext({0x106e4e2f8?, 0x1400011c018?}, 0x14000ce1b38)
	/src/pkg/cli/context.go:40 +0x1a8
github.com/siderolabs/talos/cmd/talosctl/pkg/talos/global.(*Args).WithClientNoNodes(0x0?, 0x0?, {0x0?, 0x0?, 0x0?})
	/src/cmd/talosctl/pkg/talos/global/client.go:34 +0x68
github.com/siderolabs/talos/cmd/talosctl/pkg/talos/global.(*Args).WithClient(0x0?, 0x0?, {0x0?, 0x0?, 0x0?})
	/src/cmd/talosctl/pkg/talos/global/client.go:76 +0x40
github.com/siderolabs/talos/cmd/talosctl/cmd/talos.WithClient(...)
	/src/cmd/talosctl/cmd/talos/root.go:46
github.com/siderolabs/talos/cmd/talosctl/cmd/talos.glob..func17(0x108455100?, {0x14000e42140?, 0x2?, 0x2?})
	/src/cmd/talosctl/cmd/talos/dashboard.go:40 +0x38
github.com/spf13/cobra.(*Command).execute(0x108455100, {0x14000e42120, 0x2, 0x2})
	/.cache/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x10844de00)
	/.cache/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/.cache/mod/github.com/spf13/cobra@v1.6.1/command.go:977
github.com/siderolabs/talos/cmd/talosctl/cmd.Execute()
	/src/cmd/talosctl/cmd/root.go:53 +0x334
main.main()
	/src/cmd/talosctl/main.go:19 +0x24
```

### Environment

- Talos version: v1.4.5
- Kubernetes version: v1.27.2
- Platform: Apple MacBook M1 Pro

**Comment by si458** [comment]
are you sure you have the mac version downloaded?
i had this issue with windows and WSL
i downloaded the windows version to begin with as i used powershell
then i switched to WSL(ubuntu) for trying stuff but i kept running the windows.exe version in WSL and it would give me this issue every so often
once i downloaded the linux version in WSL the errors vanished

**Comment by si458** [comment]
https://github.com/siderolabs/talos/releases/download/v1.4.5/talosctl-darwin-arm64
you need the darwin ARM64 version as you have the M1 Pro chip

**Comment by smira** [comment]
I think the issue is valid, `talosctl dashboard` should never even try to open this file when running as a CLI.
