### ISSUE TITLE
Talosctl dashboard ProcCmdline panic

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#7437]
## Bug Report

MACOS client got:

`panic: open /proc/cmdline: no such file or directory`

### Logs

```
# talosctl dashboard
panic: open /proc/cmdline: no such file or directory

goroutine 1 [running]:
github.com/siderolabs/go-procfs/procfs.ProcCmdline.func1()
        /.cache/mod/github.com/siderolabs/go-procfs@v0.1.1/procfs/cmdline.go:129 +0x78
sync.(*Once).doSlow(0x140009c69a0?, 0xe0?)
        /toolchain/go/src/sync/once.go:74 +0x104
sync.(*Once).Do(...)
        /toolchain/go/src/sync/once.go:65
github.com/siderolabs/go-procfs/procfs.ProcCmdline()
        /.cache/mod/github.com/siderolabs/go-procfs@v0.1.1/procfs/cmdline.go:126 +0x3c
github.com/siderolabs/talos/internal/pkg/dashboard.(*ConfigURLGrid).readTemplateFromKernelArgs(0x14000882340?)
        /src/internal/pkg/dashboard/configurl.go:123 +0x1c
github.com/siderolabs/talos/internal/pkg/dashboard.NewConfigURLGrid({0x10758e368, 0x14000e0a1b0}, 0x14000001e00)
```

### Environment

- Talos version: v1.4.5

**Comment by smira** [comment]
This should be fixed in 1.4.6.
