### ISSUE TITLE
Empty secrets file crashes config generation

### ISSUE THREAD

**Issue by jeroenvermeulen** [siderolabs/talos#7599]
## Bug Report

Empty secrets file crashes config generation.

### Description

Expected: An error that the secrets.yaml is empty.

### Logs

```
$ rm  secrets.yaml
$ touch  secrets.yaml
$ talosctl  gen  config  cluster_name  https://1.2.3.4:6443  --with-secrets secrets.yaml

generating PKI and tokens
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x824734]

goroutine 1 [running]:
github.com/siderolabs/talos/pkg/machinery/config/types/v1alpha1/generate.NewInput({0xfffff78cd633, 0xc}, {0xfffff78cd640, 0x14}, {0x26a80e5, 0x6}, 0x4000db29f0, {0x40000bd8c0, 0x7, 0x5e?})
	/src/pkg/machinery/config/types/v1alpha1/generate/generate.go:634 +0x244
github.com/siderolabs/talos/pkg/machinery/config/types/v1alpha1/bundle.NewConfigBundle({0x40003925c0, 0x4, 0x40?})
	/src/pkg/machinery/config/types/v1alpha1/bundle/bundle.go:106 +0x280
github.com/siderolabs/talos/cmd/talosctl/cmd/mgmt/gen.V1Alpha1Config({0x40000bd8c0, 0x7, 0x8}, {0xfffff78cd633, 0xc}, {0xfffff78cd640, 0x14}, {0x26a80e5?, 0xffffffffffffffff?}, {0x0, ...}, ...)
	/src/cmd/talosctl/cmd/mgmt/gen/config.go:163 +0x26c
github.com/siderolabs/talos/cmd/talosctl/cmd/mgmt/gen.writeV1Alpha1Config({0x40000bd880, 0x2, 0x0?})
	/src/cmd/talosctl/cmd/mgmt/gen/config.go:237 +0x934
github.com/siderolabs/talos/cmd/talosctl/cmd/mgmt/gen.NewConfigCmd.func1(0x4000896600?, {0x40000bd880?, 0x2, 0x4})
	/src/cmd/talosctl/cmd/mgmt/gen/config.go:94 +0x88
github.com/spf13/cobra.(*Command).execute(0x4000896600, {0x40000bd840, 0x4, 0x4})
	/.cache/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x4594c40)
	/.cache/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/.cache/mod/github.com/spf13/cobra@v1.6.1/command.go:977
github.com/siderolabs/talos/cmd/talosctl/cmd.Execute()
	/src/cmd/talosctl/cmd/root.go:53 +0x30c
main.main()
	/src/cmd/talosctl/main.go:19 +0x24
```
	
### Environment

- Talos version: 
```
Client:
	Tag:         v1.4.7
	SHA:         a1ee7612
	Built:
	Go version:  go1.20.6
	OS/Arch:     linux/arm64
Server:
	NODE:        142.132.243.215
	Tag:         v1.4.7
	SHA:         a1ee7612
	Built:
	Go version:  go1.20.6
	OS/Arch:     linux/amd64
	Enabled:     RBAC
```
- Kubernetes version: K8S v1.16.7
- Platform: Problem occurs both on:
  - macOS Ventura 13.5 with `talosctl` from Homebrew
  - Ubuntu 22.04.3 LTS with `talosctl` from Github

**Comment by EraKin575** [comment]
@smira can I work on this? I am new to this project and am very interested

**Comment by smira** [comment]
@EraKin575 sure, please do that!

**Comment by EraKin575** [comment]
@smira  In my case, it doesnt give an error. 
![image](https://github.com/siderolabs/talos/assets/100225222/b8189585-d517-4d1f-9336-44e356959fcd)

**Comment by jeroenvermeulen** [comment]
@EraKin575 Indeed the error seems already fixed.
Back in the beginning of August Talos 1.4.7 was the latest, now we already have 1.5.3.
You guys are moving fast!

**Comment by EraKin575** [comment]
![image](https://github.com/siderolabs/talos/assets/100225222/789ee9c4-d9d7-4caa-95c7-8fffedd30510)
strange. When I populated secrets.yaml with some data, then it gives the error

**Comment by jeroenvermeulen** [comment]
Ah good find, we can still crash `talosctl` this way:
```
$ echo "cluster:" >secrets.yaml
$ talosctl  gen  config  cluster_name  https://1.2.3.4:6443  --with-secrets secrets.yaml
generating PKI and tokens
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x104ac6cc0]

goroutine 1 [running]:
github.com/siderolabs/talos/pkg/machinery/config/generate.(*Input).init(0x14000803380)
	/src/pkg/machinery/config/generate/init.go:41 +0x2c0
github.com/siderolabs/talos/pkg/machinery/config/generate.(*Input).Config(0x16bd9f6a4?, 0xc?)
	/src/pkg/machinery/config/generate/generate.go:127 +0x2c
github.com/siderolabs/talos/pkg/machinery/config/bundle.NewBundle({0x1400081d280, 0x4, 0x40?})
	/src/pkg/machinery/config/bundle/bundle.go:122 +0x304
github.com/siderolabs/talos/cmd/talosctl/cmd/mgmt/gen.GenerateConfigBundle({0x1400071ed80, 0x7, 0x8}, {0x16bd9f6a4, 0xc}, {0x16bd9f6b1, 0x14}, {0x105d25136?, 0xffffffffffffffff?}, {0x0, ...}, ...)
	/src/cmd/talosctl/cmd/mgmt/gen/config.go:164 +0x28c
github.com/siderolabs/talos/cmd/talosctl/cmd/mgmt/gen.writeConfig({0x1400071ed00, 0x2, 0x0?})
	/src/cmd/talosctl/cmd/mgmt/gen/config.go:245 +0xa6c
github.com/siderolabs/talos/cmd/talosctl/cmd/mgmt/gen.NewConfigCmd.func1(0x14000486600?, {0x1400071ed00?, 0x2, 0x4})
	/src/cmd/talosctl/cmd/mgmt/gen/config.go:95 +0x90
github.com/spf13/cobra.(*Command).execute(0x14000486600, {0x1400071ecc0, 0x4, 0x4})
	/.cache/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x107ebe4a0)
	/.cache/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/.cache/mod/github.com/spf13/cobra@v1.7.0/command.go:1001
github.com/siderolabs/talos/cmd/talosctl/cmd.Execute()
	/src/cmd/talosctl/cmd/root.go:53 +0x334
main.main()
	/src/cmd/talosctl/main.go:19 +0x24
```
Version info:	
```
$ talosctl version --client
Client:
	Tag:         v1.5.3
	SHA:         cb21c671
	Built:
	Go version:  go1.20.8
	OS/Arch:     darwin/arm64
```

**Comment by EraKin575** [comment]
@jeroenvermeulen aside from the issue, shouldn't we have a general empty file check? The check "failed to load secrets bundle" seems only specific for secrets from the code I checked

**Comment by jeroenvermeulen** [comment]
Don't know, I am not so involved in the internals of Talos (golang).
What I do know is you should try to avoid a nil pointer exception crash.
