### ISSUE TITLE
Talos dashboard panics after certain amount of time

### ISSUE THREAD

**Issue by tmojzes** [siderolabs/talos#7645]
### Description
I am using 'talosctl dashboard' in my local development environment to view logs.
From time to time, it panics, which could be due to a bug in the dashboard code.
For this to occur, all you have to do is keep the dashboard running.
### Logs
```bash
❯ talosctl dashboard 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x21aedb0]

goroutine 41 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/.cache/mod/github.com/rivo/tview@v0.0.0-20230621164836-6cc0565babaf/application.go:251 +0x4d
panic({0x26efd40, 0x46945c0})
	/toolchain/go/src/runtime/panic.go:884 +0x213
github.com/siderolabs/talos/internal/pkg/dashboard/components.(*ProcessTable).OnAPIDataChange(0xc000390d80, {0xc00081e2c8?, 0x8?}, 0x21a8c28?)
	/src/internal/pkg/dashboard/components/tables.go:103 +0x690
github.com/siderolabs/talos/internal/pkg/dashboard.(*MonitorGrid).OnAPIDataChange(0xc000a7c380?, {0xc00081e2c8, 0x8}, 0x2?)
	/src/internal/pkg/dashboard/monitor.go:95 +0x51
github.com/siderolabs/talos/internal/pkg/dashboard.(*Dashboard).processAPIData(0xc000390c60)
	/src/internal/pkg/dashboard/dashboard.go:448 +0x24e
github.com/siderolabs/talos/internal/pkg/dashboard.(*Dashboard).startDataHandler.func2.3()
	/src/internal/pkg/dashboard/dashboard.go:403 +0x1d
github.com/rivo/tview.(*Application).QueueUpdateDraw.func1()
	/.cache/mod/github.com/rivo/tview@v0.0.0-20230621164836-6cc0565babaf/application.go:763 +0x26
github.com/rivo/tview.(*Application).Run(0xc0002da460)
	/.cache/mod/github.com/rivo/tview@v0.0.0-20230621164836-6cc0565babaf/application.go:389 +0x9c2
github.com/siderolabs/talos/internal/pkg/dashboard.Run.func2()
	/src/internal/pkg/dashboard/dashboard.go:335 +0x4d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/.cache/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/.cache/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```
### Environment

- Talos version: 
```bash
  Client:
	  Tag:         v1.5.0
	  SHA:         429a2de8
	  Built:       
	  Go version:  go1.20.7
	  OS/Arch:     linux/amd64
  Server:
	  NODE:        10.5.0.2
	  Tag:         v1.5.0
	  SHA:         429a2de8
	  Built:       
	  Go version:  go1.20.7
	  OS/Arch:     linux/amd64
	  Enabled:     RBAC
```
- Kubernetes version:
```bash
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```
- Platform: QEMU

**Comment by utkuozdemir** [comment]
Thanks for reporting, it is a bug we will look into.
